export enum beatmap_property {
    beatmap_size = 'beatmap_size',
    artist = 'artist',
    artist_unicode = 'artist_unicode',
    title = 'title',
    title_unicode = 'title_unicode',
    creator = 'creator',
    difficulty = 'difficulty',
    audio_filename = 'audio_filename',
    beatmap_md5 = 'beatmap_md5',
    osu_filename = 'osu_filename',
    ranked_status = 'ranked_status',
    number_hitcircles = 'number_hitcircles',
    number_sliders = 'number_sliders',
    number_spinners = 'number_spinners',
    mod_date = 'mod_date',
    beatmap_stats = 'beatmap_stats',
    slider_velocity = 'slider_velocity',
    star_rating_std = 'star_rating_std',
    star_rating_taiko = 'star_rating_taiko',
    star_rating_ctb = 'star_rating_ctb',
    star_rating_mania = 'star_rating_mania',
    drain_time = 'drain_time',
    total_time = 'total_time',
    preview_time = 'preview_time',
    timing_points = 'timing_points',
    beatmap_id = 'beatmap_id',
    beatmapset_id = 'beatmapset_id',
    thread_id = 'thread_id',
    grade_achieved_std = 'grade_achieved_std',
    grade_achieved_taiko = 'grade_achieved_taiko',
    grade_achieved_ctb = 'grade_achieved_ctb',
    grade_achieved_mania = 'grade_achieved_mania',
    local_offset = 'local_offset',
    stack_laniecy = 'stack_laniecy',
    gamemode = 'gamemode',
    source = 'source',
    tags = 'tags',
    online_offset = 'online_offset',
    font_title = 'font_title',
    is_unplayed = 'is_unplayed',
    last_played = 'last_played',
    is_OSZ2 = 'is_OSZ2',
    folder_name = 'folder_name',
    last_checked_repository_time = 'last_checked_repository_time',
    is_ignore_hit_sounds = 'is_ignore_hit_sounds',
    is_ignore_skin = 'is_ignore_skin',
    is_disable_storyboard = 'is_disable_storyboard',
    is_disable_video = 'is_disable_video',
    is_visual_override = 'is_visual_override',
    mod_time = 'mod_time',
    mania_scroll = 'mania_scroll'
}

export const all_beatmap_properties = [
    beatmap_property.beatmap_size,
    beatmap_property.artist,
    beatmap_property.artist_unicode,
    beatmap_property.title,
    beatmap_property.title_unicode,
    beatmap_property.creator,
    beatmap_property.difficulty,
    beatmap_property.audio_filename,
    beatmap_property.beatmap_md5,
    beatmap_property.osu_filename,
    beatmap_property.ranked_status,
    beatmap_property.number_hitcircles,
    beatmap_property.number_sliders,
    beatmap_property.number_spinners,
    beatmap_property.mod_date,
    beatmap_property.beatmap_stats,
    beatmap_property.slider_velocity,
    beatmap_property.star_rating_std,
    beatmap_property.star_rating_taiko,
    beatmap_property.star_rating_ctb,
    beatmap_property.star_rating_mania,
    beatmap_property.drain_time,
    beatmap_property.total_time,
    beatmap_property.preview_time,
    beatmap_property.timing_points,
    beatmap_property.beatmap_id,
    beatmap_property.beatmapset_id,
    beatmap_property.thread_id,
    beatmap_property.grade_achieved_std,
    beatmap_property.grade_achieved_taiko,
    beatmap_property.grade_achieved_ctb,
    beatmap_property.grade_achieved_mania,
    beatmap_property.local_offset,
    beatmap_property.stack_laniecy,
    beatmap_property.gamemode,
    beatmap_property.source,
    beatmap_property.tags,
    beatmap_property.online_offset,
    beatmap_property.font_title,
    beatmap_property.is_unplayed,
    beatmap_property.last_played,
    beatmap_property.is_OSZ2,
    beatmap_property.folder_name,
    beatmap_property.last_checked_repository_time,
    beatmap_property.is_ignore_hit_sounds,
    beatmap_property.is_ignore_skin,
    beatmap_property.is_disable_storyboard,
    beatmap_property.is_disable_video,
    beatmap_property.is_visual_override,
    beatmap_property.mod_time,
    beatmap_property.mania_scroll
]; 

export const none_beatmap_properties = [];

export enum score_property {
    gamemode = 'gamemode',
    score_version = 'score_version',
    beatmap_md5 = 'beatmap_md5',
    playername = 'playername',
    replay_md5 = 'replay_md5',
    count_300 = 'count_300',
    count_100 = 'count_100',
    count_50 = 'count_50',
    count_geki = 'count_geki',
    count_katu = 'count_katu',
    count_miss = 'count_miss',
    scores = 'scores',
    combo = 'combo',
    is_fc = 'is_fc',
    mods = 'mods',
    /**
     * Notice: in **scores.db** hp_bar always empty
     */
    hp_bar = 'hp_bar',  
    date = 'date',
    /**
     * Notice: in **scores.db** replay_data always empty
     */
    replay_data = 'replay_data',
    online_id = 'online_id',
    target_practice_accuracy = 'target_practice_accuracy'
}

export const all_score_properties = [
    score_property.gamemode,
    score_property.score_version,
    score_property.beatmap_md5,
    score_property.playername,
    score_property.replay_md5,
    score_property.count_300,
    score_property.count_100,
    score_property.count_50,
    score_property.count_geki,
    score_property.count_katu,
    score_property.count_miss,
    score_property.scores,
    score_property.combo,
    score_property.is_fc,
    score_property.mods,
    score_property.hp_bar,
    score_property.date,
    score_property.replay_data,
    score_property.online_id,
    score_property.target_practice_accuracy
];

export const none_score_properties = [];

export enum osu_file_beatmap_property {
    general_block = 'general_block',
    editor_block = 'editor_block',
    metadata_block = 'metadata_block',
    difficulty_block = 'difficulty_block',
    events_block = 'events_block',
    timing_points_block = 'timing_points_block',
    colors_block = 'colors_block',
    hit_objects_block = 'hit_objects_block',
}

export const all_osu_file_properties = [
    osu_file_beatmap_property.general_block,
    osu_file_beatmap_property.editor_block,
    osu_file_beatmap_property.metadata_block,
    osu_file_beatmap_property.difficulty_block,
    osu_file_beatmap_property.events_block,
    osu_file_beatmap_property.timing_points_block,
    osu_file_beatmap_property.colors_block,
    osu_file_beatmap_property.hit_objects_block
]